### ISSUE TITLE
Add margin to X axis.

### ISSUE THREAD

**Issue by scammi** [scammi/PVModel#13]
![Screenshot_20210429-174940_pvmodel](https://user-images.githubusercontent.com/40045101/118192019-e3915000-b41b-11eb-848f-14ac897f71e6.jpg)

**Comment by scacchipa** [comment]
I strongly recommend updating the version gradle for a easier project deployment.

**Comment by scammi** [comment]
[I will try this today.](https://stackoverflow.com/questions/17727645/how-to-update-gradle-in-android-studio)

**Comment by scacchipa** [comment]
Implement factorFont and marginsFactor in order to determinate the size of fonts and margins in relations to the window size.

*** Please, check in diferente screen sizes and probe changing the factors.

**Comment by scacchipa** [comment]
The working branch is GrapherUpgrade.

**Comment by scammi** [comment]
Great, thanks !
